### ISSUE TITLE
Test with USB reader hardware

### ISSUE THREAD

**Issue by outergod** [e-user/flatpak-ausweisapp2#2]
Find out whether ccid, acsccid and pcsc-cyberjack are needed to support it properly. Follow-up to #1 @misery

**Comment by misery** [comment]
Yes, I have a lot hardware here.
It looks like flatpak uses my local pcscd outside of the flatpak... is it possible to use an internal pcscd if the user has no pcscd?

**Comment by outergod** [comment]
Could you please try removing `  - --socket=pcsc` and run with that? @misery

**Comment by jhasse** [comment]
Without `--socket=pscs` I'm getting the following error when viewing USB card readers in the settings:

```
card_pcsc  2020.04.23 14:39:38.028 25 W ...ManagerPlugIn::updateReaders(card/pcsc/PcscReaderManagerPlugIn.cpp:121) : Cannot update readers, returnCode: 2148532227
card_pcsc  2020.04.23 14:39:38.028 25   ...ManagerPlugIn::updateReaders(card/pcsc/PcscReaderManagerPlugIn.cpp:147) : got SCARD_E_INVALID_HANDLE, trying to restart plugin
card_pcsc  2020.04.23 14:39:38.028 25   ...eaderManagerPlugIn::startScan(card/pcsc/PcscReaderManagerPlugIn.cpp:59) : SCardEstablishContext: "Scard_E_No_Service"
card_pcsc  2020.04.23 14:39:38.028 25 W ...eaderManagerPlugIn::startScan(card/pcsc/PcscReaderManagerPlugIn.cpp:62) : Not started: Cannot establish context
```

I've tried to build a Flatpak with bundled pcscd and had to build libusb like this:

```
		{
			"name": "libusb",
			"config-opts": [
				"--disable-static",
				"--disable-udev"
			],
			"cleanup": [
				"/lib/*.la",
				"/lib/pkgconfig",
				"/include"
			],
			"sources": [
				{
					"type": "archive",
					"url": "https://github.com/libusb/libusb/archive/v1.0.22.tar.gz",
					"sha256": "3500f7b182750cd9ccf9be8b1df998f83df56a39ab264976bdb3307773e16f48"
				}
			],
			"post-install": [
				"install -Dm644 COPYING /app/share/licenses/libusb/COPYING"
			]
		},
```

I've also added `--device=all` for the permissions, but never could get it to work in the end. Maybe you have an idea.

**Comment by allisonkarlitskaya** [comment]
I have a system `pcsc-lite-1.9.0-1.fc32.x86_64` (Fedora 32 Silverblue) and everything "just works" with my simple USB reader.

**Comment by outergod** [comment]
@jhasse does it maybe work with the system version of pcsc-lite @allisonkarlitskaya has installed above?

**Comment by outergod** [comment]
This seems to be working now on the official Flathub version, so I'm closing this.
